export const metadata = {
  title:
    "Contact Surya Vruksha Property Junction | Real Estate Experts in Doddaballapura, Rajanukunte & Devanahalli",
  description:
    "Get in touch with Surya Vruksha Property Junction for trusted real estate services in Doddaballapura, Rajanukunte, and Devanahalli. Contact us for property buying, selling, or consulting assistance near Bangalore North.",
  icons: {
    icon: ["/mrglogo.png"],
    apple: ["/mrglogo.png?v=4"],
    shortcut: ["/mrglogo.png"],
  },
  metadataBase: new URL("https://www.SuryaVruksha.com"),
  category: "Real Estate",
  keywords: [
    "Contact Surya Vruksha Property Junction",
    "Real estate contact Doddaballapura",
    "Contact real estate consultants Rajanukunte",
    "Property advisors Devanahalli contact",
    "Surya Vruksha Property Junction phone number",
    "Surya Vruksha Property Junction email",
    "Real estate Bangalore North contact",
    "Talk to property consultants Bangalore",
    "Real estate agents contact near Doddaballapura",
    "Get in touch Surya Vruksha Property Junction",
    "Visit Surya Vruksha Property Junction office",
    "Contact property dealers Rajanukunte",
    "Property help Doddaballapura",
    "Bangalore North property consultation contact",
    "About Surya Vruksha Property Junction",
    "Real estate company in Doddaballapura",
    "Real estate consultants in Rajanukunte",
    "Real estate agents in Devanahalli",
    "Property dealers in Doddaballapura",
    "Property experts near Bangalore",
    "Real estate company Bangalore North",
    "Surya Vruksha Property Junction team",
    "Property advisors in Doddaballapura",
    "Real estate services in Rajanukunte",
    "Agricultural land consultants Devanahalli",
    "Top real estate company Bangalore North",
    "Real estate about page SEO",
    "Trusted property consultants Bangalore",
    "Surya Vruksha Property Junction About Us",
    "Sites in/near Doddaballapura",
    "Plots in/near Doddaballapura",
    "Residential Sites in/near Doddaballapura",
    "Resident Plots in/near Doddaballapura",
    "Commercial Sites in/near Doddaballapura",
    "Commercial Plots in/near Doddaballapura",
    "Agricultural land near Doddaballapura",
    "Sites in/near Rajanukunte",
    "Plots in/near Rajanukunte",
    "Residential Sites in/near Rajanukunte",
    "Resident Plots in/near Rajanukunte",
    "Commercial Sites in/near Rajanukunte",
    "Commercial Plots in/near Rajanukunte",
    "Agricultural land near Rajanukunte",
    "Sites in/near Devanahalli",
    "Plots in/near Devanahalli",
    "Residential Sites in/near Devanahalli",
    "Resident Plots in/near Devanahalli",
    "Commercial Sites in/near Devanahalli",
    "Commercial Plots in/near Devanahalli",
    "Agricultural land near Devanahalli",
    "Sites in/near Nandi Hills",
    "Plots in/near Nandi Hills",
    "Residential Sites in/near Nandi Hills",
    "Resident Plots in/near Nandi Hills",
    "Commercial Sites in/near Nandi Hills",
    "Commercial Plots in/near Nandi Hills",
    "Agricultural land near Nandi Hills",
  ],
  authors: [
    {
      name: "Chandan, for mVruksha Softwares",
      url: "https://www.mvruksha.com",
    },
  ],
  creator: [
    {
      name: "mVruksha Softwares",
      url: "https://www.mvruksha.com",
    },
  ],
  openGraph: {
    title: "Contact Surya Vruksha Property Junction | Property Advisors Near Bangalore",
    description:
      "Need property assistance? Reach out to Surya Vruksha Property Junction for expert real estate consulting and support in Doddaballapura, Rajanukunte, and Devanahalli.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
    site_name: "SuryaVruksha.com",
    url: "https://www.SuryaVruksha.com/contact",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Contact Surya Vruksha Property Junction | Trusted Real Estate Experts",
    description:
      "Connect with Surya Vruksha Property Junction for expert guidance in buying or selling residential, commercial, or agricultural land near Bangalore.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
  },
  canonical: "https://www.SuryaVruksha.com/contact",
  robots: "index, follow",
  xRobotsTag: "index, follow",
  language: "en",
  rating: "General",
};
