export const metadata = {
  title:
    "Commercial Plots for Sale | Doddaballapura, Rajanukunte & Devanahalli",
  description:
    "Discover prime commercial plots for sale in Doddaballapura, Rajanukunte, and Devanahalli. Invest in high-potential locations near Bangalore with Surya Vruksha Property Junction' expert real estate advisory.",
  icons: {
    icon: ["/mrglogo.png"],
    apple: ["/mrglogo.png?v=4"],
    shortcut: ["/mrglogo.png"],
  },
  metadataBase: new URL("https://www.SuryaVruksha.com"),
  category: "Real Estate",
  keywords: [
    "Commercial plots for sale Doddaballapura",
    "Commercial land Rajanukunte",
    "Business property Devanahalli",
    "Investment plots near Bangalore",
    "Commercial property Bangalore North",
    "Plots for shops and offices Doddaballapura",
    "Surya Vruksha Property Junction commercial listings",
    "Buy commercial land Devanahalli",
    "Rajanukunte commercial investment",
    "Verified commercial plots Bangalore",
    "Commercial real estate consultants",
    "Commercial land near airport Bangalore",
    "Shops and office plots for sale",
    "Real estate near Devanahalli airport",
    "High ROI commercial plots",
    "About Surya Vruksha Property Junction",
    "Real estate company in Doddaballapura",
    "Real estate consultants in Rajanukunte",
    "Real estate agents in Devanahalli",
    "Property dealers in Doddaballapura",
    "Property experts near Bangalore",
    "Real estate company Bangalore North",
    "Surya Vruksha Property Junction team",
    "Property advisors in Doddaballapura",
    "Real estate services in Rajanukunte",
    "Agricultural land consultants Devanahalli",
    "Top real estate company Bangalore North",
    "Real estate about page SEO",
    "Trusted property consultants Bangalore",
    "Surya Vruksha Property Junction About Us",
    "Sites in/near Doddaballapura",
    "Plots in/near Doddaballapura",
    "Residential Sites in/near Doddaballapura",
    "Resident Plots in/near Doddaballapura",
    "Commercial Sites in/near Doddaballapura",
    "Commercial Plots in/near Doddaballapura",
    "Agricultural land near Doddaballapura",
    "Sites in/near Rajanukunte",
    "Plots in/near Rajanukunte",
    "Residential Sites in/near Rajanukunte",
    "Resident Plots in/near Rajanukunte",
    "Commercial Sites in/near Rajanukunte",
    "Commercial Plots in/near Rajanukunte",
    "Agricultural land near Rajanukunte",
    "Sites in/near Devanahalli",
    "Plots in/near Devanahalli",
    "Residential Sites in/near Devanahalli",
    "Resident Plots in/near Devanahalli",
    "Commercial Sites in/near Devanahalli",
    "Commercial Plots in/near Devanahalli",
    "Agricultural land near Devanahalli",
    "Sites in/near Nandi Hills",
    "Plots in/near Nandi Hills",
    "Residential Sites in/near Nandi Hills",
    "Resident Plots in/near Nandi Hills",
    "Commercial Sites in/near Nandi Hills",
    "Commercial Plots in/near Nandi Hills",
    "Agricultural land near Nandi Hills",
  ],
  authors: [
    {
      name: "Chandan, for mVruksha",
      url: "https://mvruksha.com",
    },
  ],
  creator: [
    {
      name: "mVruksha Softwares",
      url: "https://www.mvruksha.com",
    },
  ],
  openGraph: {
    title:
      "Buy Commercial Plots in Doddaballapura, Rajanukunte & Devanahalli | Surya Vruksha Property Junction",
    description:
      "Browse prime commercial properties ideal for shops, offices, and investments in top Bangalore North locations. Trusted by hundres of customers.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
    site_name: "SuryaVruksha.com",
    url: "https://www.SuryaVruksha.com/commercial-plots",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Commercial Land for Sale | Bangalore North Investment Properties",
    description:
      "Explore high-potential commercial plots in Doddaballapura, Rajanukunte & Devanahalli. Get expert guidance from Surya Vruksha Property Junction.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
  },
  canonical: "https://www.SuryaVruksha.com/commercial-plots",
  robots: "index, follow",
  xRobotsTag: "index, follow",
  language: "en",
  rating: "General",
};
