export const metadata = {
  title:
    "Property Services | Real Estate Consulting & Advisory in Bangalore North",
  description:
    "Surya Vruksha Property Junction offers trusted real estate services including property buying, selling, legal consulting, documentation, and investment advisory in Doddaballapura, Rajanukunte, and Devanahalli.",
  icons: {
    icon: ["/mrglogo.png"],
    apple: ["/mrglogo.png?v=4"],
    shortcut: ["/mrglogo.png"],
  },
  metadataBase: new URL("https://www.SuryaVruksha.com"),
  category: "Real Estate Services",
  keywords: [
    "Real estate services Bangalore North",
    "Property consulting Doddaballapura",
    "Real estate advisory Rajanukunte",
    "Buy and sell land Devanahalli",
    "Legal support for land purchase",
    "Property registration services",
    "Land documentation Bangalore",
    "Investment consulting in real estate",
    "Real estate agents Bangalore North",
    "Property evaluation and valuation",
    "Trusted real estate advisors",
    "End-to-end property solutions",
    "Commercial and residential real estate support",
    "Agricultural land consulting",
    "Surya Vruksha Property Junction services",
    "About Surya Vruksha Property Junction",
    "Real estate company in Doddaballapura",
    "Real estate consultants in Rajanukunte",
    "Real estate agents in Devanahalli",
    "Property dealers in Doddaballapura",
    "Property experts near Bangalore",
    "Real estate company Bangalore North",
    "Surya Vruksha Property Junction team",
    "Property advisors in Doddaballapura",
    "Real estate services in Rajanukunte",
    "Agricultural land consultants Devanahalli",
    "Top real estate company Bangalore North",
    "Real estate about page SEO",
    "Trusted property consultants Bangalore",
    "Surya Vruksha Property Junction About Us",
    "Sites in/near Doddaballapura",
    "Plots in/near Doddaballapura",
    "Residential Sites in/near Doddaballapura",
    "Resident Plots in/near Doddaballapura",
    "Commercial Sites in/near Doddaballapura",
    "Commercial Plots in/near Doddaballapura",
    "Agricultural land near Doddaballapura",
    "Sites in/near Rajanukunte",
    "Plots in/near Rajanukunte",
    "Residential Sites in/near Rajanukunte",
    "Resident Plots in/near Rajanukunte",
    "Commercial Sites in/near Rajanukunte",
    "Commercial Plots in/near Rajanukunte",
    "Agricultural land near Rajanukunte",
    "Sites in/near Devanahalli",
    "Plots in/near Devanahalli",
    "Residential Sites in/near Devanahalli",
    "Resident Plots in/near Devanahalli",
    "Commercial Sites in/near Devanahalli",
    "Commercial Plots in/near Devanahalli",
    "Agricultural land near Devanahalli",
    "Sites in/near Nandi Hills",
    "Plots in/near Nandi Hills",
    "Residential Sites in/near Nandi Hills",
    "Resident Plots in/near Nandi Hills",
    "Commercial Sites in/near Nandi Hills",
    "Commercial Plots in/near Nandi Hills",
    "Agricultural land near Nandi Hills",
  ],
  authors: [
    {
      name: "Chandan HM",
      url: "https://chandan21.vercel.app",
    },
  ],
  creator: [
    {
      name: "CDevXGen Team",
      url: "https://www.cdevxgen.com",
    },
  ],
  openGraph: {
    title:
      "Real Estate Services in Doddaballapura, Rajanukunte & Devanahalli | Surya Vruksha Property Junction",
    description:
      "Explore reliable and professional real estate services for buying, selling, consulting, and legal support in prime Bangalore North areas.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
    site_name: "SuryaVruksha.com",
    url: "https://www.SuryaVruksha.com/services",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Property Services | Trusted Real Estate Consulting & Support",
    description:
      "Comprehensive property services in Doddaballapura, Rajanukunte & Devanahalli. Get expert help with buying, selling, legal documentation, and investment planning.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
  },
  canonical: "https://www.SuryaVruksha.com/services",
  robots: "index, follow",
  xRobotsTag: "index, follow",
  language: "en",
  rating: "General",
};
