export const metadata = {
  title:
    "Properties for Sale | Residential, Commercial & Farmland in Doddaballapura, Rajanukunte, Nandi Hills & Devanahalli",
  description:
    "Explore a wide range of verified residential sites, commercial plots, and farmland properties in Doddaballapura, Rajanukunte, Nandi Hills and Devanahalli. Buy the best property with Surya Vruksha Property Junction' expert guidance.",
  icons: {
    icon: ["/mrglogo.png"],
    apple: ["/mrglogo.png?v=4"],
    shortcut: ["/mrglogo.png"],
  },
  metadataBase: new URL("https://www.SuryaVruksha.com"),
  category: "Real Estate",
  keywords: [
    "Properties in Doddaballapura",
    "Properties in Rajanukunte",
    "Properties in Devanahalli",
    "Residential plots in Doddaballapura",
    "Commercial sites in Rajanukunte",
    "Farmland near Devanahalli",
    "Land for sale in Bangalore North",
    "Buy residential sites Doddaballapura",
    "Commercial plots Rajanukunte",
    "Agricultural land Doddaballapura",
    "Property listings Bangalore North",
    "Residential property Devanahalli",
    "Surya Vruksha Property Junction listings",
    "Verified plots in Doddaballapura",
    "Farmland for sale Bangalore outskirts",
    "Real estate in Rajanukunte",
    "Top property dealers Devanahalli",
    "Buy land near Bangalore airport",
    "About Surya Vruksha Property Junction",
    "Real estate company in Doddaballapura",
    "Real estate consultants in Rajanukunte",
    "Real estate agents in Devanahalli",
    "Property dealers in Doddaballapura",
    "Property experts near Bangalore",
    "Real estate company Bangalore North",
    "Surya Vruksha Property Junction team",
    "Property advisors in Doddaballapura",
    "Real estate services in Rajanukunte",
    "Agricultural land consultants Devanahalli",
    "Top real estate company Bangalore North",
    "Real estate about page SEO",
    "Trusted property consultants Bangalore",
    "Surya Vruksha Property Junction About Us",
    "Sites in/near Doddaballapura",
    "Plots in/near Doddaballapura",
    "Residential Sites in/near Doddaballapura",
    "Resident Plots in/near Doddaballapura",
    "Commercial Sites in/near Doddaballapura",
    "Commercial Plots in/near Doddaballapura",
    "Agricultural land near Doddaballapura",
    "Sites in/near Rajanukunte",
    "Plots in/near Rajanukunte",
    "Residential Sites in/near Rajanukunte",
    "Resident Plots in/near Rajanukunte",
    "Commercial Sites in/near Rajanukunte",
    "Commercial Plots in/near Rajanukunte",
    "Agricultural land near Rajanukunte",
    "Sites in/near Devanahalli",
    "Plots in/near Devanahalli",
    "Residential Sites in/near Devanahalli",
    "Resident Plots in/near Devanahalli",
    "Commercial Sites in/near Devanahalli",
    "Commercial Plots in/near Devanahalli",
    "Agricultural land near Devanahalli",
    "Sites in/near Nandi Hills",
    "Plots in/near Nandi Hills",
    "Residential Sites in/near Nandi Hills",
    "Resident Plots in/near Nandi Hills",
    "Commercial Sites in/near Nandi Hills",
    "Commercial Plots in/near Nandi Hills",
    "Agricultural land near Nandi Hills",
  ],
  authors: [
    {
      name: "Chandan, for mVruksha",
      url: "https://mvruksha.com",
    },
  ],
  creator: [
    {
      name: "mVruksha Softwares",
      url: "https://www.mvruksha.com",
    },
  ],
  openGraph: {
    title:
      "Explore Residential, Commercial & Farmland Properties | Surya Vruksha Property Junction",
    description:
      "Browse premium properties in Doddaballapura, Rajanukunte, Nandi Hills & Devanahalli. Choose from residential, commercial, and agricultural land with Surya Vruksha Property Junction.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
    site_name: "SuryaVruksha.com",
    url: "https://www.SuryaVruksha.com/properties",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Properties for Sale | Doddaballapura, Rajanukunte, Nandi Hills & Devanahalli",
    description:
      "Discover the best properties in North Bangalore. Residential, commercial, and farmland options available from Surya Vruksha Property Junction.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
  },
  canonical: "https://www.SuryaVruksha.com/properties",
  robots: "index, follow",
  xRobotsTag: "index, follow",
  language: "en",
  rating: "General",
};
