export const metadata = {
  title:
    "Client Testimonials | Surya Vruksha Property Junction | Trusted Real Estate Advisors",
  description:
    "Read real testimonials from happy clients of Surya Vruksha Property Junction. Discover why we’re the trusted choice for buying, selling, and investing in properties near Doddaballapura, Rajanukunte, Nandi Hills, and Devanahalli.",
  icons: {
    icon: ["/mrglogo.png"],
    apple: ["/mrglogo.png?v=4"],
    shortcut: ["/mrglogo.png"],
  },
  metadataBase: new URL("https://www.SuryaVruksha.com"),
  category: "Real Estate",
  keywords: [
    "Surya Vruksha Property Junction reviews",
    "Client testimonials real estate",
    "Customer feedback MR Geniune",
    "Trusted property consultants Bangalore",
    "Best property agents Doddaballapura",
    "Real estate reviews Rajanukunte, Nandi Hills",
    "Devanahalli property feedback",
    "Real estate success stories",
    "Property buyer experiences",
    "Client satisfaction real estate",
    "Reliable land consultants Bangalore North",
    "Genuine property services testimonials",
    "About Surya Vruksha Property Junction",
    "Real estate company in Doddaballapura",
    "Real estate consultants in Rajanukunte, Nandi Hills",
    "Real estate agents in Devanahalli",
    "Property dealers in Doddaballapura",
    "Property experts near Bangalore",
    "Real estate company Bangalore North",
    "Surya Vruksha Property Junction team",
    "Property advisors in Doddaballapura",
    "Real estate services in Rajanukunte, Nandi Hills",
    "Agricultural land consultants Devanahalli",
    "Top real estate company Bangalore North",
    "Real estate about page SEO",
    "Trusted property consultants Bangalore",
    "Surya Vruksha Property Junction About Us",
    "Sites in/near Doddaballapura",
    "Plots in/near Doddaballapura",
    "Residential Sites in/near Doddaballapura",
    "Resident Plots in/near Doddaballapura",
    "Commercial Sites in/near Doddaballapura",
    "Commercial Plots in/near Doddaballapura",
    "Agricultural land near Doddaballapura",
    "Sites in/near Rajanukunte, Nandi Hills",
    "Plots in/near Rajanukunte, Nandi Hills",
    "Residential Sites in/near Rajanukunte, Nandi Hills",
    "Resident Plots in/near Rajanukunte, Nandi Hills",
    "Commercial Sites in/near Rajanukunte, Nandi Hills",
    "Commercial Plots in/near Rajanukunte, Nandi Hills",
    "Agricultural land near Rajanukunte, Nandi Hills",
    "Sites in/near Devanahalli",
    "Plots in/near Devanahalli",
    "Residential Sites in/near Devanahalli",
    "Resident Plots in/near Devanahalli",
    "Commercial Sites in/near Devanahalli",
    "Commercial Plots in/near Devanahalli",
    "Agricultural land near Devanahalli",
    "Sites in/near Nandi Hills",
    "Plots in/near Nandi Hills",
    "Residential Sites in/near Nandi Hills",
    "Resident Plots in/near Nandi Hills",
    "Commercial Sites in/near Nandi Hills",
    "Commercial Plots in/near Nandi Hills",
    "Agricultural land near Nandi Hills",
  ],
  authors: [
    {
      name: "Chandan, for mVruksha",
      url: "https://mvruksha.com",
    },
  ],
  creator: [
    {
      name: "mVruksha Softwares",
      url: "https://www.mvruksha.com",
    },
  ],
  openGraph: {
    title: "What Our Clients Say | Surya Vruksha Property Junction Testimonials",
    description:
      "See how Surya Vruksha Property Junction helped clients find the right residential, commercial, and agricultural properties in Bangalore North.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
    site_name: "SuryaVruksha.com",
    url: "https://www.SuryaVruksha.com/testimonials",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Trusted by Clients | Surya Vruksha Property Junction Testimonials",
    description:
      "Our satisfied clients share their experiences in finding the best properties in Doddaballapura, Rajanukunte, Nandi Hills & Devanahalli with Surya Vruksha Property Junction.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
  },
  canonical: "https://www.SuryaVruksha.com/testimonials",
  robots: "index, follow",
  xRobotsTag: "index, follow",
  language: "en",
  rating: "General",
};
