export const metadata = {
  title:
    "Agricultural Land for Sale | Farmland near Nandi Hills, Doddaballapura, Rajanukunte & Devanahalli",
  description:
    "Looking for farmland or agricultural land near Bangalore? Explore verified agricultural land for sale near Nandi Hills, Doddaballapura, Rajanukunte & Devanahalli with Surya Vruksha Property Junction – your trusted land consultants.",
  icons: {
    icon: ["/mrglogo.png"],
    apple: ["/mrglogo.png?v=4"],
    shortcut: ["/mrglogo.png"],
  },
  metadataBase: new URL("https://www.SuryaVruksha.com"),
  category: "Real Estate",
  keywords: [
    "Agricultural land for sale Doddaballapura",
    "Farmland near Rajanukunte",
    "Agricultural land Devanahalli",
    "Buy farmland near Bangalore",
    "Farmland plots for sale Bangalore North",
    "MR Geniune agricultural properties",
    "Fertile farmland near Bangalore",
    "Doddaballapura agriculture land",
    "Rajanukunte farmland for investment",
    "Devanahalli agricultural plots",
    "Farm plots for sale near airport",
    "Organic farmland near Bangalore",
    "Surya Vruksha Property Junction farmland listings",
    "Farm land for investment Bangalore",
    "About Surya Vruksha Property Junction",
    "Real estate company in Doddaballapura",
    "Real estate consultants in Rajanukunte",
    "Real estate agents in Devanahalli",
    "Property dealers in Doddaballapura",
    "Property experts near Bangalore",
    "Real estate company Bangalore North",
    "Surya Vruksha Property Junction team",
    "Property advisors in Doddaballapura",
    "Real estate services in Rajanukunte",
    "Agricultural land consultants Devanahalli",
    "Top real estate company Bangalore North",
    "Real estate about page SEO",
    "Trusted property consultants Bangalore",
    "Surya Vruksha Property Junction About Us",
    "Sites in/near Doddaballapura",
    "Plots in/near Doddaballapura",
    "Residential Sites in/near Doddaballapura",
    "Resident Plots in/near Doddaballapura",
    "Commercial Sites in/near Doddaballapura",
    "Commercial Plots in/near Doddaballapura",
    "Agricultural land near Doddaballapura",
    "Sites in/near Rajanukunte",
    "Plots in/near Rajanukunte",
    "Residential Sites in/near Rajanukunte",
    "Resident Plots in/near Rajanukunte",
    "Commercial Sites in/near Rajanukunte",
    "Commercial Plots in/near Rajanukunte",
    "Agricultural land near Rajanukunte",
    "Sites in/near Devanahalli",
    "Plots in/near Devanahalli",
    "Residential Sites in/near Devanahalli",
    "Resident Plots in/near Devanahalli",
    "Commercial Sites in/near Devanahalli",
    "Commercial Plots in/near Devanahalli",
    "Agricultural land near Devanahalli",
    "Sites in/near Nandi Hills",
    "Plots in/near Nandi Hills",
    "Residential Sites in/near Nandi Hills",
    "Resident Plots in/near Nandi Hills",
    "Commercial Sites in/near Nandi Hills",
    "Commercial Plots in/near Nandi Hills",
    "Agricultural land near Nandi Hills",
  ],
  authors: [
    {
      name: "Chandan, for mVruksha",
      url: "https://mvruksha.com",
    },
  ],
  creator: [
    {
      name: "mVruksha Softwares",
      url: "https://www.mvruksha.com",
    },
  ],
  openGraph: {
    title:
      "Buy Agricultural Land in Doddaballapura, Rajanukunte & Devanahalli | Surya Vruksha Property Junction",
    description:
      "Explore affordable and verified agricultural land and farmland options near Bangalore with expert consultation by Surya Vruksha Property Junction.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
    site_name: "SuryaVruksha.com",
    url: "https://www.SuryaVruksha.com/agricultural-land",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Farmland for Sale | Doddaballapura, Rajanukunte, Devanahalli",
    description:
      "Find agricultural land and farmland for investment near Bangalore North. Surya Vruksha Property Junction offers reliable deals and expert guidance.",
    images: [
      {
        url: "/mrglogo.jpg",
        alt: "Surya Vruksha Property Junction Logo",
      },
    ],
  },
  canonical: "https://www.SuryaVruksha.com/agricultural-land",
  robots: "index, follow",
  xRobotsTag: "index, follow",
  language: "en",
  rating: "General",
};
